Settings:
  # 해당 플러그인이 보내는 메시지의 PREFIX 설정
  prefix: "&f[ &eDLR &f] "

  #---------- UI 설정 ----------#

  # 스킬 슬롯, 무기슬롯 고정 또는 자유
  # true = 고정, false = 자유
  ui-immovable: true

  # true 일경우의 설정

  # 위치를 -1로 설정할 경우 빈 슬롯이 됩니다.
  # 슬롯 : 0 ~ 8
  #1번 스킬 위치
  ui-skill-1: 0
  #2번 스킬 위치
  ui-skill-2: 1
  #3번 스킬 위치
  ui-skill-3: 2
  #4번 스킬 위치
  ui-skill-4: 3
  #5번 스킬 위치
  ui-skill-5: 4
  #6번 스킬 위치
  ui-skill-6: 5
  #7번 스킬 위치
  ui-skill-7: 6
  #8번 스킬 위치
  ui-skill-8: 7


  # 무기 변경 방식 - 권장 설정은 true 입니다.
  # true = 주 무기, 보조 무기, 근접 무기가 순서대로 돌아가며 변경됩니다.
  # false = 주 무기, 보조 무기, 근접 무기의 슬롯을 지정해줘야 합니다.
  ui-weapon-switch: true

  # true 일경우의 설정

  ui-weapon: 8

  # false 일경우의 설정
#  ui-primary-weapon: 0
#  ui-secondary-weapon: 1
#  ui-melee-weapon: 2

  #---------- 커맨드 설정 ----------#

  # /스포너
  cmd-spawner: "스포너"
  # /몹
  cmd-mobs: "몹"

  #---------- 스포너 설정 ----------#

  # 스포너를 생성할 위치.
  # STAND : 자신이 서있는 위치
  # LOOK : 자신이 바라보고 있는 가장 가까운 블럭의 위치 (최대 30블럭)
  set-spawner-point: STAND

  # 스포너 생성시 자동으로 타이머를 설정할지의 여부
  # true, false
  set-spawner-auto-timer: true

  # 스포너 생성시 자동으로 타이머를 설정할 때 설정될 타이머 기본값 (초 단위)
  set-spawner-default-timer: 30

  # 스포너 생성후 몇마리씩 소환되게 할지 설정을 안했을때 기본값
  # 모든 스포너 해당.
  set-spawner-default-per-spawn: 1


  #---------- 파티 설정 ----------#

  # 파티 인원 제한 (최대 수치 : 127)
  max-party-size: 4

  # 파티원 간 경험치 공유 거리 (블럭, 미터) (최대 수치 : 32767) (-1로 설정시 공유기능 사용 안함, 0으로 설정시 거리 제한 없이 공유됨)
  max-exp-sharing-distance: 50

  # 파티원에게 공유되는 경험치 계수
  exp-sharing-coefficient: 0.7



